### ISSUE TITLE
abiFilters and arm-v8a

### ISSUE THREAD

**Issue by berkerogluu** [yuger/VPN2018#11]
Hello yuger, abiFilters just added armeabi-v7a. Is app possible to run on arm-v8a  ?

**Comment by yuger** [comment]
yes
arm-v8a is compatible with armeabi-v7a

**Comment by berkerogluu** [comment]
Thank you I understand now. For example, Galaxy S9 SD845 SoC's supported:  armeabi, armeabi-v7a and arm-v8a :)
