### ISSUE TITLE
android:sharedUserId="android.uid.system"  vpn无法正常工作

### ISSUE THREAD

**Issue by EvanZch** [yuger/VPN2018#14]
apk需要系统权限，添加 android:sharedUserId="android.uid.system"后发现 vpn无法正常工作，取消后没问题

**Comment by kso1990** [comment]
managed to solve this problem? How?

**Comment by EvanZch** [comment]
Put the vpn part of the code, as an apk, the system app is connected via aidi

**Comment by kso1990** [comment]
> Put the vpn part of the code, as an apk, the system app is connected via aidi

hi, can you explain in more detail what do you mean?

**Comment by dh123321** [comment]
> apk需要系统权限，添加 android:sharedUserId="android.uid.system"后发现 vpn无法正常工作，取消后没问题

您好，我最近的一个项目也遇到了这个问题，能请问下找到这个问题的原因和解决办法了吗？谢谢。
